tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rapsite.views.home', name='home'),
    # url(r'^rapsite/', include('rapsite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^$', 'pages.views.MainHomePage'),
    (r'^albums/$', 'album.views.AlbumsAll'),
    (r'^albums/(?P<albumslug>.*)/$', 'album.views.SpecificAlbum'),
    (r'^rappers/(?P<rapperslug>.*)/$', 'album.views.SpecificRapper'),
    (r'^register/$', 'siteusers.views.SiteUserRegistration'),
    (r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done'), 
    (r'^resetpassword/$', 'django.contrib.auth.views.password_reset'), 
    (r'^reset/(?<uidb36>[0-9A-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
    (r'^login/$', 'siteusers.views.LoginRequest'),
    ('^logout/$', 'siteusers.views.LogoutRequest'),
)

album/models.py
from django.db import models

COAST_CHOICES = (
	('W', 'West Coast'), 
	('E', 'East Coast'),
	('S', 'The South'),
)

class Album(models.Model):
	name = models.CharField(max_length=200)
	slug = models.SlugField(unique=True)
	rapper = models.ForeignKey('Rapper')
	coast = models.CharField(max_length=1, choices=COAST_CHOICES)
	description = models.TextField(blank=True)
	image1 = models.ImageField(upload_to="images/albumthumbs/", blank=True)

	def __unicode__(self):
		return self.name

class Rapper(models.Model):
	name = models.CharField(max_length=200)
	slug = models.SlugField(unique=True)
	description = models.TextField(blank=True)

	def __unicode__(self):
		return self.name

siteusers/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User

class SiteUser(models.Model):
	user = models.OneToOneField(User)
	birthday = models.DateField()
	name = models.CharField(max_length=100)

	def __unicode__(self):
		return self.name

# create user object to attach to SiteUser
#def create_siteuser_user_callback(sender, instance, **kwargs):
#	siteuser, new = SiteUser.objects.get_or_create(user=instance)
#post_save.connect(create_siteuser_user_callback, User)

templates/albumsall.html
{% extends "base.html" %}
{% block content %}
	<div id="albumslist">
		{% for album in albums %}
		<p><a href="/albums/{{ album.slug }}/"><img src = "{{ album.image1.url }}" /> {{ album }} </a></p>
		{% endfor %}
	</div>



{% endblock %}

templates/base.html
<html>
<head>
	<link rel="stylesheet" type="text/css" href="/static/CSS/video1.css" />
	{% block extrahead %}{% endblock %}
</head>
<body>
<div id="pageContainer">
	<div id="nav_tab_right">
		{% if user.is_authenticated %}<p><a href='/logout/'>Logout</a></p>{% else %}<p><a href='/login/'>Login</a></p>{% endif %}
	</div>
	{% block content %}
	{% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
		<div id="home_copy">
				{{ homepage.homecopy|safe }}
		</div>
		<a href="/albums">View the Albums List!</a>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
<form action="" method"post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}
<div class="register_div">
	{% if form.username.errors %}<p class="error">{{ form.username.errors }}</p>{% endif %}
	<p><label for="username"{% if form.username.errors %} class="error"{% endif %}>Username</label></p>
	<p>{{ form.username }}</p>
</div>
<div class="register_div">
	{% if form.password.errors %}<p class="error">{{form.password.errors }}</p>{% endif %}
	<p><label for="password"{% if form.password.errors %} class="errors"{% endif %}>Password</label></p>
	<p>{{ form.password }}</p>
</div>
<p><input type="submit" alt="register" /></p>
</form>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block extrahead %}
	<script scr="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js" type="text/javascript" type="text/javascript"></script>
	<script scr="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js" type="text/javascript" type="text/javascript"></script>
	<script>
        $(function() {
                $( "#id_birthday" ).datepicker();
        });
        </script>
{% endblock %}
{% block content %}
<form action="" method"post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}
<div class="register_div">
	{% if form.username.errors %}<p class="error">{{ form.username.errors }}</p>{% endif %}
	<p><label for="username"{% if form.username.errors %} class="error"{% endif %}>Username:</label></p>
	<p>{{ form.username }}</p>
</div>
<div class="register_div">
	{% if form.email.errors %}<p class="error">{{form.email.errors }}</p>{% endif %}
	<p><label for="email"{% if form.email.errors %} class="error"{% endif %}>Email</label></p>
	<p>{{ form.email }}</p>
</div>
<div class="register_div">
	{% if form.password.errors %}<p class="error">{{form.password.errors }}</p>{% endif %}
	<p><label for="password"{% if form.password.errors %} class="errors"{% endif %}>Password</label></p>
	<p>{{ form.password }}</p>
</div>
<div class="register_div">
	{% if form.password1.errors %}<p class="error">{{form.password1.errors }}</p>{% endif %}
	<p><label for="password1"{% if form.password1.errors %} class="error"{% endif %}>Verify: Password</label></p>
	<p>{{ form.password1 }}</p>
<div class="register_div">
        {% if form.birthday.errors %}<p class="error">{{ form.birthday.errors }}</p>{% endif %}
        <p><label for="birthday"{% if form.birthday.errors %} class="error"{% endif %}>Birthday:</label></p>
        <p>{{ form.birthday }}</p>
</div>
<div class="register_div">
        {% if form.name.errors %}<p class="error">{{ form.name.errors }}</p>{% endif %}
        <p><label for="name"{% if form.name.errors %} class="error"{% endif %}>Name:</label></p>
        <p>{{ form.name }}</p>
</div>
<p><input type="submit" alt="register" /></p>
</form>
{% endblock %}

templates/singlealbum.html
{% extends "base.html" %}
{% block content %}
	<div id="singlealbum">
		<p>Name: {{ album }}</p>
		<p>Coast: {{ album.get_coast_display }}</p>
		<p>Rapper: <a href="/rappers/{{ album.rapper.slug }}/"> {{ album.rapper }} </a></p>
	</div>

{% endblock %}

templates/singlerapper.html
{% extends "base.html" %}
{% block content %}
	<div id="albumslist">
		<h2> Albums from {{ albums.0.rapper }}</h2>
		{% for album in albums %}
		<p><a href="/albums/{{ album.slug }}/"> {{ album }}</a></p>
		{% endfor %}
	</div>



{% endblock %}